### ISSUE TITLE
Create a pull request template 

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/CodeFemme#8]
For help refer to [link](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
While creating the pull request template, I am not sure where should i Make the template visible since there are different names to be used for the file depending upon visibility. Which one do I carry on with?

![capture](https://user-images.githubusercontent.com/45824817/51096303-89e3d100-17e1-11e9-85e6-fc0ee85457d7.PNG)

Also please help me out with what the content of a pull request template should be?

**Comment by Archies11** [comment]
@opencodebot unclaim

**Comment by Jahanvi21** [comment]
@opencodebot claim

**Comment by chi50800** [comment]
@opencodebot claim

**Comment by chi50800** [comment]
@opencodebot claim

**Comment by chi50800** [comment]
what all things should be there in PR template?

**Comment by Anupam-dagar** [comment]
@chi50800 It's good to refer to some other projects and see there PR template rather than directly asking for it.
It should have a section which tells to add description, a fixes # issue, a screenshot or gif and finally testing plan.
